JAIL_TOP_LEFT_X8: EQU 17
JAIL_TOP_LEFT_Y:  EQU 140
JAIL_TOP_LEFT:    EQU 40*JAIL_TOP_LEFT_Y+JAIL_TOP_LEFT_X8
JAIL_HEIGHT:      EQU 30
JAIL_WIDTH:       EQU 8

TESZT:
    LD DE, JAIL_TOP_LEFT
    CALL TESZT_HLINE_DE
    LD DE, JAIL_TOP_LEFT+40
    CALL TESZT_HLINE_DE	
    LD DE, JAIL_TOP_LEFT+JAIL_HEIGHT*40
    CALL TESZT_HLINE_DE
    LD DE, JAIL_TOP_LEFT+JAIL_HEIGHT*40+40
    CALL TESZT_HLINE_DE	

    LD DE, JAIL_TOP_LEFT-1
    CALL TESZT_VLINE_DE
    LD DE, JAIL_TOP_LEFT+JAIL_WIDTH+1
    CALL TESZT_VLINE_DE
    RET

TESZT_HLINE_DE:
    LD A, 255
    LD HL, (DCB_HM_2)
    ADD HL, DE
    PUSH HL
    POP DE
    INC DE
    LD BC, JAIL_WIDTH
    LD (HL), A
    LDIR
    RET

TESZT_VLINE_DE:
    LD A, %10100101
    LD HL, (DCB_HM_2)
    ADD HL, DE
    LD DE, 40
    LD B, JAIL_HEIGHT+2
TESZT_VLINE_LOOP:
    LD (HL), A
    ADD HL, DE
    DJNZ TESZT_VLINE_LOOP
    RET
